In [1]:
  #importing the numpy library
import numpy as np

In [2]:
#Create an array with 10 equally spaced numbers between 0 and 1.

array = np.linspace(0, 1, 10)

print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [3]:
#Create a 1D array of 20 random integers between 1 and 100.

array = np.random.randint(1, 101, 20)

print(array)

[67 98  4 20 97 46 58 67 55 45 93 68 50  7 33 92 77 31 45 92]


In [4]:
#Create a 2D array with the shape (4, 4) filled with the value 7.

array_2d = np.full((4, 4), 7)

print(array_2d)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [5]:
#Create a 1D array of 10 elements with the same value, 3.14.

array = np.full(10, 3.14)

print(array)

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [6]:
#Create a 2D array with the shape (3, 3) with values ranging from 1 to 9.

# Create a 1D array with values ranging from 1 to 9
array_1d = np.arange(1, 10)

# Reshape the 1D array into a 2D array with shape (3, 3)
array_2d = array_1d.reshape(3, 3)

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Create two arrays: a = [1, 3, 5, 7, 9] and b = [2, 4, 6, 8, 10]. Perform element-wise subtraction.

import numpy as np

a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

subtraction = a - b

print(subtraction)



[-1 -1 -1 -1 -1]


In [8]:
#Multiply array a by 3: a = [2, 4, 6, 8].

a = np.array([2, 4, 6, 8])

result = a * 3

print("Original array a:", a)
print("Result after multiplying by 3:", result)

Original array a: [2 4 6 8]
Result after multiplying by 3: [ 6 12 18 24]


In [9]:
#Divide array a by 2: a = [10, 20, 30, 40].

a = np.array([10, 20, 30, 40])


result = a / 2

print("Original array a:", a)
print("Result after dividing by 2:", result)

Original array a: [10 20 30 40]
Result after dividing by 2: [ 5. 10. 15. 20.]


In [10]:
#Find the element-wise modulus of two arrays: a = [5, 10, 15], b = [2, 3, 4].

a = np.array([5, 10, 15])
b = np.array([2, 3, 4])

result = np.remainder(a, b)

print("Array a:", a)
print("Array b:", b)
print("Element-wise modulus:", result)

Array a: [ 5 10 15]
Array b: [2 3 4]
Element-wise modulus: [1 1 3]


In [11]:
#Create two arrays: a = [1, 2, 3], b = [4, 5, 6]. Compute the dot product.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

print("Array a:", a)
print("Array b:", b)
print("Dot product:", dot_product)

Array a: [1 2 3]
Array b: [4 5 6]
Dot product: 32


In [12]:
#Create two matrices: a = [[2, 3], [4, 5]] and b = [[1, 0], [0, 1]]. Perform matrix multiplication.

a = np.array([[2, 3], [4, 5]])
b = np.array([[1, 0], [0, 1]])

result = np.matmul(a, b)


print("Matrix a:\n", a)
print("Matrix b:\n", b)
print("Result of matrix multiplication:\n", result)

Matrix a:
 [[2 3]
 [4 5]]
Matrix b:
 [[1 0]
 [0 1]]
Result of matrix multiplication:
 [[2 3]
 [4 5]]


In [13]:
#Multiply a 3x3 matrix with a 3x1 vector.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([1, 2, 3])

result = np.matmul(matrix, vector)

print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Result of matrix-vector multiplication:\n", result)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [1 2 3]
Result of matrix-vector multiplication:
 [14 32 50]


In [14]:
#Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random integers.



# Create a 4x4 identity matrix
identity_matrix = np.eye(4)

# Create a 4x4 matrix with random integers (between 0 and 9 for example)
random_matrix = np.random.randint(0, 10, size=(4, 4))

# Perform matrix multiplication
result = np.matmul(identity_matrix, random_matrix)

print("Identity Matrix:\n", identity_matrix)
print("\nRandom Matrix:\n", random_matrix)
print("\nResult of matrix multiplication:\n", result)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Matrix:
 [[0 3 2 6]
 [8 7 0 2]
 [9 7 0 6]
 [4 4 9 4]]

Result of matrix multiplication:
 [[0. 3. 2. 6.]
 [8. 7. 0. 2.]
 [9. 7. 0. 6.]
 [4. 4. 9. 4.]]


In [15]:
#Perform matrix multiplication on two 3x3 matrices: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]].

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

result = np.matmul(a, b)

print("Matrix a:\n", a)
print("\nMatrix b:\n", b)
print("\nResult of matrix multiplication:\n", result)

Matrix a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix b:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [16]:
#Create a 2x3 matrix and a 3x2 matrix. Perform matrix multiplication.

matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

result = np.matmul(matrix_a, matrix_b)

print("Matrix a:\n", matrix_a)
print("\nMatrix b:\n", matrix_b)
print("\nResult of matrix multiplication:\n", result)

Matrix a:
 [[1 2 3]
 [4 5 6]]

Matrix b:
 [[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
 [[ 58  64]
 [139 154]]


In [17]:
#Create a 1D array: array = [10, 20, 30]. Subtract a scalar value, 5, using broadcasting.

array = np.array([10, 20, 30])


result = array - 5

print(result)

[ 5 15 25]


In [18]:
#Create a 3x3 array and a 3x1 array. Add them using broadcasting.

array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])


array_3x1 = np.array([[1],
                      [2],
                      [3]])


result = array_3x3 + array_3x1

print(result)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [19]:
#Divide a 4x4 array by a scalar value, 2, using broadcasting.

array_4x4 = np.array([[8, 16, 24, 32],
                      [40, 48, 56, 64],
                      [72, 80, 88, 96],
                      [104, 112, 120, 128]])


result = array_4x4 / 2

print(result)

[[ 4.  8. 12. 16.]
 [20. 24. 28. 32.]
 [36. 40. 44. 48.]
 [52. 56. 60. 64.]]


In [20]:
#Create a 3x3 array and add 3 to each element using broadcasting.

array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

result = array_3x3 + 3

print(result)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#Multiply a 1D array of shape (5,) by a 2D array of shape (5, 5) using broadcasting.

array_1d = np.array([1, 2, 3, 4, 5])


array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])


result = array_2d * array_1d

print(result)

[[  1   4   9  16  25]
 [  6  14  24  36  50]
 [ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]]


In [22]:
#Calculate the median of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


median_value = np.median(data)

print("Median of the array:", median_value)

Median of the array: 5.5


In [23]:
#Calculate the mode of the array: data = [1, 2, 2, 3, 4, 4, 4, 5, 6].



# Create the data array
data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6])

# Calculate the mode using np.argmax
# Find the most frequent value's index
most_frequent_idx = np.argmax(np.bincount(data))

# Get the mode value from the data array
mode = data[most_frequent_idx]

# Print the mode
print(mode)


4


In [24]:
#Calculate the range of the array: data = [10, 20, 30, 40, 50].

data = np.array([10, 20, 30, 40, 50])

# Calculate the range
range_value = np.max(data) - np.min(data)

print("Range of the array:", range_value)

Range of the array: 40


In [25]:
#Calculate the 25th percentile of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 25th percentile
percentile_25 = np.percentile(data, 25)

print("25th percentile of the array:", percentile_25)

25th percentile of the array: 3.25


In [26]:
#Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2, 4, 6, 8, 10].

a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])


correlation_matrix = np.corrcoef(a, b)
correlation_coefficient = correlation_matrix[0, 1]

print("Correlation coefficient between arrays a and b:", correlation_coefficient)

Correlation coefficient between arrays a and b: 0.9999999999999999


In [27]:
#Reshape a 1D array of 12 elements to a 3x4 array.

array_1d = np.arange(12)  # Example array: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


array_2d = array_1d.reshape(3, 4)

print("3x4 array:\n", array_2d)

3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
#Reshape a 2D array of shape (6, 2) to (3, 4).


array_2d_6x2 = np.arange(12).reshape(6, 2)  # Example array: [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]

# Reshape the 2D array to (3, 4)
array_reshaped = array_2d_6x2.reshape(3, 4)

print("Reshaped array (3x4):\n", array_reshaped)

Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
#Create a 4x4 array and flatten it.

array_4x4 = np.arange(16).reshape(4, 4)  # Example array: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

flattened_array = array_4x4.flatten()

print("Flattened array:\n", flattened_array)

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [30]:
#Reshape a 3D array of shape (2, 3, 4) to (4, 3, 2).

array_3d = np.arange(24).reshape(2, 3, 4)  # Example array with shape (2, 3, 4)

# Reshape the 3D array to (4, 3, 2)
reshaped_array = array_3d.reshape(4, 3, 2)

print("Reshaped array (4, 3, 2):\n", reshaped_array)


Reshaped array (4, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [31]:
#Reshape a 1D array to a 2D array with 1 row and many columns.

array_1d = np.arange(10)  # Example array: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array_2d = array_1d.reshape(1, -1)

print("2D array with 1 row and many columns:\n", array_2d)

2D array with 1 row and many columns:
 [[0 1 2 3 4 5 6 7 8 9]]


In [32]:
#Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.

a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

# Perform element-wise division
result = a / b

print("Element-wise division result:\n", result)

Element-wise division result:
 [0.5        0.75       0.83333333]


In [33]:
#Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Perform element-wise modulus
result = a % b

print("Element-wise modulus result:\n", result)

Element-wise modulus result:
 [0 1 1]


In [34]:
#Add 10 to each element in the array: a = [1, 2, 3, 4, 5].

a = np.array([1, 2, 3, 4, 5])

# Add 10 to each element
result = a + 10

print("Array after adding 10:\n", result)


Array after adding 10:
 [11 12 13 14 15]


In [35]:
#Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].

b = np.array([10, 20, 30, 40, 50])

# Subtract 5 from each element
result = b - 5

print("Array after subtracting 5:\n", result)


Array after subtracting 5:
 [ 5 15 25 35 45]


In [36]:
#Square each element in the array: c = [1, 2, 3, 4, 5].

c = np.array([1, 2, 3, 4, 5])

# Square each element
squared_result = c ** 2

print("Array after squaring each element:\n", squared_result)


Array after squaring each element:
 [ 1  4  9 16 25]


In [37]:
#Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access the element at [1, 1, 1].

array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])

element = array_3d[1, 1, 1]

print("Element at [1, 1, 1]:", element)

Element at [1, 1, 1]: 11


In [38]:
#Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]].

array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])

first_layer = array_3d[0]

print("First layer of the 3D array:\n", first_layer)


First layer of the 3D array:
 [[1 2 3]
 [4 5 6]]


In [39]:
#Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

last_row = array_2d[-1]

print("Elements in the last row:\n", last_row)

Elements in the last row:
 [70 80 90]


In [40]:
#Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

first_column = array_2d[:, 0]

print("Elements in the first column:\n", first_column)

Elements in the first column:
 [10 40 70]


In [41]:
#Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

sliced_array = array_2d[-2:, -2:]

print("Last two rows and columns:\n", sliced_array)

Last two rows and columns:
 [[50 60]
 [80 90]]


In [42]:
#Generate a random array of 20 elements with values between 0 and 1.

random_array = np.random.rand(20)

print("Random array of 20 elements with values between 0 and 1:\n", random_array)

Random array of 20 elements with values between 0 and 1:
 [0.77282924 0.77280616 0.1336177  0.20236563 0.86193466 0.44255639
 0.69957521 0.49261657 0.99415321 0.6565074  0.54257799 0.27741225
 0.3415596  0.24689842 0.24153317 0.16678676 0.79677565 0.68485616
 0.0731861  0.59405285]


In [43]:
#Create a 4x4 array with random integers between 10 and 20.

random_array = np.random.randint(10, 20, size=(4, 4))

print("4x4 array with random integers between 10 and 20:\n", random_array)

4x4 array with random integers between 10 and 20:
 [[16 10 10 19]
 [12 16 12 19]
 [14 15 17 11]
 [10 16 16 14]]


In [44]:
#Create a 3x3 array with random floats between -1 and 1.


random_array = np.random.uniform(-1, 1, size=(3, 3))

print("3x3 array with random floats between -1 and 1:\n", random_array)

3x3 array with random floats between -1 and 1:
 [[-0.98261225  0.90021921  0.41480684]
 [-0.43641202  0.05303547  0.04925278]
 [-0.71638072  0.01267401  0.67663089]]


In [45]:
#Generate an array of 15 random integers between 100 and 200.

random_array = np.random.randint(100, 200, size=15)

print("Array of 15 random integers between 100 and 200:\n", random_array)

Array of 15 random integers between 100 and 200:
 [182 188 132 162 128 189 114 133 133 130 176 194 150 145 181]


In [46]:
#5. Create a 5x5 array with random floats between 0 and 10.

random_array = np.random.uniform(0, 10, size=(5, 5))

print("5x5 array with random floats between 0 and 10:\n", random_array)

5x5 array with random floats between 0 and 10:
 [[3.26066636 1.32997362 1.23383829 5.27075981 8.60240721]
 [6.67641675 7.64180254 9.31372773 7.22575226 3.69943473]
 [3.39173875 0.67053019 1.46117327 9.32071655 2.12958104]
 [1.31515727 7.68753073 0.24218956 3.42717692 4.01154742]
 [6.94319673 1.23503813 7.62603376 3.30819075 8.19892574]]


In [47]:
#Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

stacked_array = np.vstack((a, b))

print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
#Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

stacked_array = np.hstack((a, b))

print("Horizontally stacked array:\n", stacked_array)

Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]


In [49]:
#Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenated_array = np.concatenate((a, b))

print("Concatenated array:\n", concatenated_array)

Concatenated array:
 [1 2 3 4 5 6]


In [50]:
#Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10, 11, 12], [13, 14, 15], [16, 17, 18]].

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

concatenated_array = np.vstack((a, b))

print("Concatenated array along rows:\n", concatenated_array)

Concatenated array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [51]:
#Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10, 11, 12], [13, 14, 15], [16, 17, 18]].

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

concatenated_array = np.hstack((a, b))

print("Concatenated array along columns:\n", concatenated_array)

Concatenated array along columns:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
